# Generated by Django 2.2.4 on 2019-11-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='language',
            field=models.ManyToManyField(to='example.Language'),
        ),
    ]
