# Generated by Django 2.2.4 on 2019-11-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_programmer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(default='1996-07-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='date_created',
            field=models.DateField(blank=True, default='1996-07-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
